config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root to: "movies#index"


  
  resources :movies do
    member do
      get :upload_movie_file
      get :finish_upload
      get :watch
    end
  end

  namespace :api do
    namespace :v1 do
      post "authenticate" => "users#authenticate"

      resources :movies, defaults: {format: :json}
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/api/v1/movies_controller.rb
class Api::V1::MoviesController < Api::ApiController

  def index
    @movies = Movie.watchable
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, except: [:index, :new, :create]

  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to upload_movie_file_movie_path(@movie), notice: 'Movie was successfully created. Please upload movie file' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    s3_object = get_movie_object_on_s3
    s3_object.delete unless s3_object.blank?
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #create presigned post object and use ti to upload directly to S3
  def upload_movie_file
    bucket = get_input_bucket
    @presigned_post = bucket.presigned_post({
      key: @movie.movie_file,
      success_action_status: "201",
      success_action_redirect: request.base_url + finish_upload_movie_path(@movie),
      content_type: "video/mp4"
    })
    puts @presigned_post.fields
  end

  #when upload finishes, create transcode job in AWS Elastic Transcoder
  def finish_upload
    res = @movie.create_transcode_job_hls!

    if res.error
      flash[:error] = "There was an error creating the transcode job for this movie."
    else
      @movie.update_attributes(ready_to_watch: false, transcode_error: false, transcode_hls_job_id: res.data[:job][:id])
      flash[:success] = "The transcode job was started successfully, your video will be ready when it's finished."
    end

    redirect_to movies_path
  end

  def watch

  end

  private

    #s3 client
    def get_s3_client
      Aws::S3::Resource.new(region: AWS_REGION)
    end

    #get input bucket
    def get_input_bucket
      client = get_s3_client
      buckets = client.buckets.select do |bucket| 
        bucket.name==INPUT_BUCKET
      end
      buckets.first
    end

    def get_movie_object_on_s3
      bucket = get_input_bucket
      bucket.objects.first
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:movie_name, :movie_file, :ready_to_watch)
    end
end

app/helpers/api/v1/movies_helper.rb
module Api::V1::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_name %><br>
    <%= f.text_field :movie_name %>
  </div>
  <div class="field">
    <%= f.label :movie_file %><br>
    <%= f.text_field :movie_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Movie name</th>
      <th>Movie file</th>
      <th>Ready to watch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.movie_name %></td>
        <td><%= movie.movie_file %></td>
        <td><%= movie.ready_to_watch %></td>
        <td><%= link_to 'Watch', watch_movie_path(movie) %></td> 
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie name:</strong>
  <%= @movie.movie_name %>
</p>

<p>
  <strong>Movie file:</strong>
  <%= @movie.movie_file %>
</p>

<p>
  <strong>Ready to watch:</strong>
  <%= @movie.ready_to_watch %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/movies/upload_movie_file.html.erb
<p id="notice"><%= notice %></p>
<h1>Movie file</h1>
<form action="<%= @presigned_post.url %>" method="post" enctype="multipart/form-data">
  <% @presigned_post.fields.each do |name, value| %>
    <input type="hidden" name="<%= name %>" value="<%= value %>"/>
  <% end %>
  <div class="field">
    <input type="file" name="file"/>
  </div>
  <div class="actions">
    <%= submit_tag %>
  </div>
</form>

app/views/movies/watch.html.erb
<script>
  function redirect_at_end(){  }
  </script>

<div id="video-player"> </div>


<!-- <script src="static/js/jquery-1.10.2.min.js"></script> -->
<!-- <script src="static/js/jquery.ba-throttle-debounce.min.js"></script> -->
<script>
$.ajaxSetup({
    cache: false
});

function resizeVideo(){
  if( $('#momovi_video').length ) { 
    $("#momovi_video").width($( window ).width());
    $("#momovi_video").height($( window ).height());
  }
  if( $('#momovi_video_html5_api').length ) { 
    $("#momovi_video_html5_api").width($( window ).width());
    $("#momovi_video_html5_api").height($( window ).height());
  }
}
$(window).resize( function(){
   resizeVideo();
   setTimeout(resizeVideo, 1500);
});

$( document ).ready(
  resizeVideo
);

function newplayer(data){
    var poster = data.poster
    
    var posterimg = "<div id=\"video-player\"><img id=\"momovi_video\" src=\"" +poster+ "\"></div>";
    $("#video-player").replaceWith(posterimg);
    hlsplayer(data)
}

function checkm3u8available_helper(hlsdata,depth){
  if(depth > 20){
    alert("Could not open stream");
    return
  }
  var is_msie = navigator.userAgent.toLowerCase().indexOf('msie') > -1;
  if(is_msie){
    runplayer(hlsdata);
  } else{
  var hlsurl = hlsdata.stream_url
  $.get(hlsurl,function(data,status){
      if(data.indexOf(".ts") != -1 || data.indexOf("STREAM-INF") != -1){
      runplayer(hlsdata);
      } else {
      depth=depth+1;
        setTimeout(function(){checkm3u8available_helper(hlsdata,depth)},350);
      }
     });
    }
}

function checkm3u8available(data){
  var is_available = checkm3u8available_helper(data,0);

}

function hlsplayer(data){
  checkm3u8available(data);
}
function getUrlVars()
{
    var vars = [], hash;
    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    return vars;
}

function runplayer(data) {
  var autoplay = "autoplay",
      loop = "",
      cast = "",
      controls = "controls";
  var hlsurl = data.stream_url;
  var poster = data.poster;
  var urlvars=getUrlVars();
  if(urlvars['autoplay'] != null){ 
   if(urlvars['autoplay'] == "false"){
     autoplay = ""
   }
  }
  if(urlvars['loop']){ 
    if(urlvars['loop'] == "true" ){
     loop = "loop"
   }
  }

  if(urlvars['cast']){ 
    if(urlvars['cast'] == "true" ){
     cast = "cast"
   }
  } 
  
  if( autoplay == "autoplay" ){
    if(urlvars['controls']){ 
    if(urlvars['controls'] == "false" ){
       controls = "";
    }
    }
  }
  var vidplayer = "<video "+controls + "  "+cast + "id=\"momovi_video\" class=\"video-js vjs-default-skin\" preload=\"none\" width=\"300px\" height=\"200px\" "+autoplay + " " + loop + " poster=\""+ poster + "\"    data-setup=\'{ }'\>  <source src=\""+hlsurl+"\" type=\'video/mp4\' /></video>"
  $("#video-player").replaceWith(vidplayer);
  vjs.autoSetup();
  resizeVideo();
}
</script>
<!-- <script src='modernizr.custom.82348.js' type="text/javascript" charset="utf-8"></script> -->

<div id="jsonploader"></div>

<script language="JavaScript"> 
<!--
var is_chrome = navigator.userAgent.toLowerCase().indexOf('chrome') > -1;
var is_msie = navigator.userAgent.toLowerCase().indexOf('msie') > -1;
var is_safari = navigator.userAgent.toLowerCase().indexOf('safari') > -1;
var is_idevice = (navigator.userAgent.match(/iPhone/i)) || (navigator.userAgent.match(/iPod/i));

newplayer({"stream_url": "<%= @movie.hls_playlist_url.html_safe %>","poster":""});
-->
</script>